clc
clear

%V1.0 by Manu 
% this code goes into all the files generated by the code
% "tracking_MSD_batch_dataset" and compile the results in a nice 
% excel file by Field Of View (FOV).
% run in at the root folder (where "tracking_MSD_batch_dataset" is)

%Output: DperFOW matrix
%1 sample name (aka folder name)
%2 FOV number (aka number of Tif file)
%3 total number of tracks in this FOV
%4 number of tracks passing the selection
%5 mean diffusion coefficient in the FOV
%6 sem of diffusion coefficient in the FOV

r2threhold=0.9; %threshold in r² to keep the tracks
alphathrehold=0.45; %threshold in alpha bellow which to remove tracks for Deff

nbinDeff=50; %nbins for Deff distrib
Deffmax=0.5;   %Deff max for Deff distrib in um²/s
binDeff=0:Deffmax/nbinDeff:Deffmax;
binDeff2=0:Deffmax/nbinDeff:(Deffmax-Deffmax/nbinDeff);
binDeff2=binDeff2';

%do FOW per FOW
DperFOW=cell(1,6);
q=1;
DperFOW{q,1}='sample';
DperFOW{q,2}='FOV number';
DperFOW{q,3}='total number of tracks in this FOV';
DperFOW{q,4}='number of tracks passing the selection';
DperFOW{q,5}='median diffusion coefficient in the FOV';
DperFOW{q,6}='sem of diffusion coefficient in the FOV';
%% 


q=q+1;

%cd thunderstorm_output;

%% 

files=dir('2024*.mat');
 sfiles=size(files,1);

 %% 

for r=1:sfiles
    basename=files(r).name;
    display(cat(2,'processing file ',num2str(r),' of ',num2str(sfiles)));
    load(basename);

    b=find(MSDfit(:,8)>r2threhold);
    sub=MSDfit(b,:);
    b=find(sub(:,6)>alphathrehold);
    sub=sub(b,:);
    DperFOW{q,5}=median(sub(:,4));
    DperFOW{q,6}=std(sub(:,4))/sqrt(length(sub(:,4)));
    DperFOW{q,4}=length(sub(:,4));
    DperFOW{q,3}=length(MSDfit(:,4));
    DperFOW{q,2}=cat(2,'cell #',num2str(r));
    DperFOW{q,1}=basename;


    q=q+1;
         
       

end


%% 


% Convert the cell array to a numeric array
%DperFOW_numeric = cell2mat(DperFOW);

DperFOW_table = cell2table(DperFOW(2:end,:), 'VariableNames', DperFOW(1,:));

%% 

% Write the numeric array to Excel file
writetable(DperFOW_table, '/Users/azeng/Documents/Experiments/Exp 101 GEM experiment/3T3 Bmal1 luc/timecourse/medianMSDperFOVw.xls')


